// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrwiB4TmXf3CfcIjmI4nZAdGPdH27c-0',
    appId: '1:244856579835:web:19cbbea161b28d0def725e',
    messagingSenderId: '244856579835',
    projectId: 'fashion-27017',
    authDomain: 'fashion-27017.firebaseapp.com',
    storageBucket: 'fashion-27017.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHE1F8PtV6lFJ5gupaROGGPXIZsf9PwY',
    appId: '1:244856579835:android:f256ce855f121443ef725e',
    messagingSenderId: '244856579835',
    projectId: 'fashion-27017',
    storageBucket: 'fashion-27017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pPSHcbCl7Jk4LTD7bVq6B_evFVtnvRY',
    appId: '1:244856579835:ios:fcb46d00df4bacf9ef725e',
    messagingSenderId: '244856579835',
    projectId: 'fashion-27017',
    storageBucket: 'fashion-27017.appspot.com',
    iosBundleId: 'com.example.duAnFashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9pPSHcbCl7Jk4LTD7bVq6B_evFVtnvRY',
    appId: '1:244856579835:ios:ab0160d9a5d009cfef725e',
    messagingSenderId: '244856579835',
    projectId: 'fashion-27017',
    storageBucket: 'fashion-27017.appspot.com',
    iosBundleId: 'com.example.duAnFashion.RunnerTests',
  );
}
